Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -61,6 +61,16 @@ steps:
     echo "Pushing image to ACR..."
     echo "Manually logging in to Docker..."
     echo $(acrPassword) | docker login $(acrName).azurecr.io --username $(acrUsername) --password-stdin
+    if [ $? -eq 0 ]; then
+      echo "Login successful"
+    else
+      echo "Login failed"
+      exit 1
+    fi
+    
+    echo "Tagging image..."
+    docker tag $(localImage) $(acrName).azurecr.io/$(acrImage)
+
     echo "Pushing image..."
-    docker push $(acrImage) || exit 1
-  displayName: 'Push Image to ACR'
+    docker push $(acrName).azurecr.io/$(acrImage) || exit 1
+  displayName: 'Push image to ACR'
